houses/urls.py
from django.urls import path

from houses.views import (ComponentsPageView, HomePageView, HouseDetailView,
                          HouseListView, InteriorGalleryView, NewsListView)

app_name = "houses"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("dev/", ComponentsPageView.as_view(), name="dev"),
    path("houses/", HouseListView.as_view(), name="house_list"),
    path("houses/<int:pk>/", HouseDetailView.as_view(), name="house_detail"),
    path("interiors/", InteriorGalleryView.as_view(), name="interior_gallery"),
    path("news/", NewsListView.as_view(), name="news_list"),
]

mestv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("houses.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

houses/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

from houses.utils.file_path import album_photo_path, main_photo_path

NULLABLE = {"blank": True, "null": True}


class Album(models.Model):
    """Модель альбома"""

    name = models.CharField(max_length=100, verbose_name="Название альбома")
    description = models.CharField(max_length=255, verbose_name="Описание")

    class Meta:
        verbose_name = "Альбом"
        verbose_name_plural = "Альбомы"

    def __str__(self):
        return self.name


class Photo(models.Model):
    """Модель фотографии"""

    album = models.ForeignKey(
        Album, on_delete=models.CASCADE, related_name="photos", verbose_name="Альбом"
    )
    image = ProcessedImageField(
        upload_to=album_photo_path,
        processors=[ResizeToFill(800, 600)],
        format="JPEG",
        options={"quality": 80},
        verbose_name="Фото",
    )
    description = models.CharField(max_length=255, verbose_name="Описание", **NULLABLE)

    class Meta:
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"

    def __str__(self):
        return f"Фото {self.id} из альбома {self.album.name}"


class House(models.Model):
    """Модель дома"""

    name = models.CharField(max_length=100, verbose_name="Название дома")
    description = models.TextField(verbose_name="Описание")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания", **NULLABLE
    )
    main_photo = ProcessedImageField(
        upload_to=main_photo_path,
        processors=[ResizeToFill(800, 600)],
        format="JPEG",
        options={"quality": 80},
        verbose_name="Фото",
        **NULLABLE,
    )
    album = models.OneToOneField(
        "Album", on_delete=models.SET_NULL, **NULLABLE, verbose_name="Альбом"
    )

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Дом"
        verbose_name_plural = "Дома"

    def __str__(self):
        return self.name


class Interior(models.Model):
    """Модель интерьера"""

    name = models.CharField(max_length=50, verbose_name="Название интерьера")
    description = models.CharField(max_length=255, verbose_name="Описание")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )
    main_photo = ProcessedImageField(
        upload_to=main_photo_path,
        processors=[ResizeToFill(800, 600)],
        format="JPEG",
        options={"quality": 80},
        verbose_name="Фото",
        **NULLABLE,
    )
    album = models.OneToOneField(
        "Album", on_delete=models.SET_NULL, **NULLABLE, verbose_name="Альбом"
    )

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Интерьер"
        verbose_name_plural = "Интерьеры"

    def __str__(self):
        return self.name


class News(models.Model):
    """Модель новости"""

    name = models.CharField(max_length=100, verbose_name="Название новости")
    description = models.TextField(verbose_name="Описание")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )
    main_photo = ProcessedImageField(
        upload_to=main_photo_path,
        processors=[ResizeToFill(800, 600)],
        format="JPEG",
        options={"quality": 80},
        verbose_name="Фото",
        **NULLABLE,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"


class ContactInfo(models.Model):
    """Модель контактной информации"""

    address = models.CharField(max_length=100, verbose_name="Адрес")
    phone = models.CharField(max_length=100, verbose_name="Номер телефона", **NULLABLE)
    email = models.CharField(max_length=100, verbose_name="Адрес почты", **NULLABLE)
    telegram = models.URLField(verbose_name="Ссылка на Telegram", **NULLABLE)
    whatsapp = models.URLField(verbose_name="Ссылка на WhatsApp", **NULLABLE)
    instagram = models.URLField(verbose_name="Ссылка на Instagram", **NULLABLE)

    def __str__(self):
        return f"{self.address}, {self.phone}"

    class Meta:
        verbose_name = "Контактная информация"
        verbose_name_plural = "Контактная информация"


class HeaderText(models.Model):
    """Модель для текста в header на главной странице"""

    title = models.CharField(max_length=100, verbose_name="Текст")
    is_active = models.BooleanField(
        default=False, verbose_name="Активный (начальный) текст"
    )

    class Meta:
        verbose_name = "Текст в header"
        verbose_name_plural = "Тексты в header"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.is_active:
            HeaderText.objects.filter(is_active=True).exclude(pk=self.pk).update(
                is_active=False
            )
        super().save(*args, **kwargs)

houses/views.py
from django.shortcuts import get_object_or_404
from django.views import generic

from houses.models import ContactInfo, HeaderText, House, Interior, News


class HomePageView(generic.TemplateView):
    template_name = "main.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data()

        data["title"] = "Moscow Estate - загородные дома под ключ возле Москвы"

        data["header_texts"] = HeaderText.objects.all()
        data["contact_info"] = ContactInfo.objects.first()

        data["main_houses"] = House.objects.all().order_by("?")[:4]
        data["main_interiors"] = Interior.objects.all().order_by("?")[:3]
        data["main_news"] = News.objects.order_by("-created_at").first()
        return data


class ComponentsPageView(generic.TemplateView):
    template_name = "components.html"


class HouseListView(generic.ListView):
    model = House
    queryset = House.objects.all()
    context_object_name = "houses"
    paginate_by = 8


class NewsListView(generic.ListView):
    model = News
    queryset = News.objects.all().order_by("-created_at")
    context_object_name = "news_list"
    paginate_by = 5


class HouseDetailView(generic.DetailView):
    model = House
    queryset = House.objects.all()
    context_object_name = "house"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        house = self.get_object()
        if house.album:
            context["photos"] = house.album.photos.all()
        else:
            context["photos"] = []
        return context


class InteriorGalleryView(generic.ListView):
    model = Interior
    template_name = "houses/interior_gallery.html"
    context_object_name = "interiors"

    def get_queryset(self):
        return Interior.objects.all().order_by("-created_at")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        interior_id = self.request.GET.get("interior")

        if interior_id:
            active_interior = get_object_or_404(Interior, id=interior_id)
        else:
            active_interior = Interior.objects.first()

        context["active_interior"] = active_interior
        context["photos"] = (
            active_interior.album.photos.all() if active_interior.album else []
        )
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Moscow Estate - turnkey country houses near Moscow">
    <meta name="author" content="Roman Pecheritsa">
    <title>Moscow Estate - Загородные дома под ключ возле Москвы</title>

    <link rel="stylesheet" href={% static "vendors/owl-carousel/css/owl.carousel.css" %}>
    <link rel="stylesheet" href={% static "vendors/owl-carousel/css/owl.theme.default.css" %}>
    <link rel="stylesheet" href={% static "css/ollie.css" %}>
    <link rel="stylesheet" href={% static 'css/baguetteBox.min.css' %}/>
    <link rel="stylesheet" href={% static 'css/compact-gallery.css' %}/>
    <link rel="stylesheet" href="{% static 'icons/bootstrap-icons.css' %}">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

{% include 'includes/navmenu.html' %}
{% block content %}
{% endblock %}
{% include 'includes/footer.html' %}
{% include 'includes/scroll_button.html' %}

<script src={% static "vendors/jquery/jquery-3.4.1.js" %}></script>
<script src={% static "vendors/bootstrap/bootstrap.bundle.js" %}></script>
<script src={% static "vendors/bootstrap/bootstrap.affix.js" %}></script>
<script src={% static "vendors/owl-carousel/js/owl.carousel.js" %}></script>
<script src={% static "js/ollie.js" %}></script>
<script src={% static 'js/baguetteBox.min.js' %}></script>
<script>
    baguetteBox.run('.compact-gallery', {animation: 'slideIn'});
</script>

</body>
</html>

templates/houses/house_detail.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
    <br>
    <div class="container mb-3">
        <div class="blog-wrapper">
            <div class="img-wrapper d-flex">
                <img src="{{ house.main_photo.url }}" alt="{{ house.name }}">
            </div>
            <div class="container">
                <h4 class="blog-title">{{ house.name }}</h4>
                <h6 class="xs-font mb-0">Описание</h6>
                <p>{{ house.description }}</p>
            </div>
        </div>
    </div>
    <section class="gallery-block compact-gallery">
        <div class="container">
            <div class="heading">
                <h4>Галерея</h4>
            </div>
            <div class="row no-gutters">
                {% for photo in photos %}
                    <div class="col-md-6 col-lg-4 item zoom-on-hover">
                        <a class="lightbox" href={{ photo.image.url }}>
                            <img class="img-fluid image scale-on-hover" src={{ photo.image.url }}>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <br>
        <br>
        <div style="text-align: center">
            <a class="btn btn-primary btn-rounded" href={% url 'houses:house_list' %}>К списку домов</a>
            <a class="btn btn-outline-primary btn-rounded" href={% url 'houses:home' %}>На главную</a>
        </div>
    </section>


{% endblock %}

templates/houses/house_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% include 'includes/navmenu.html' %}
{% block content %}
    <section class="section">
        <div class="container">
            <h6 class="xs-font mb-0">Реализованные проекты</h6>
            <h3 class="section-title pb-4">Дома</h3>
        </div>
        <div class="container-fluid mt-4">
            <div class="row">
                {% if houses %}
                    {% for house in houses %}
                        <div class="col-md-3 col-sm-6 mb-4">
                            <a href={% url 'houses:house_detail'  house.pk %} class="item expertises-item">
                                <img src="{{ house.main_photo.url }}" alt="{{ house.name }}"
                                     class="box-shadow img-fluid">
                                <h6 class="mt-3 mb-2">{{ house.name }}</h6>
                                <p class="xs-font">{{ house.description|truncate_smart:100 }}</p>
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="container">
                        <h3 class="text-center">Список пуст</h3>
                    </div>
                {% endif %}
            </div>
        </div>
        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-lg justify-content-center">
                    {% for page_num in paginator.page_range %}
                        {% if page_num == page_obj.number %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        {% endif %}
    </section>
{% endblock %}

templates/houses/interior_gallery.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block content %}
    <section class="gallery-block compact-gallery">
        <div class="container">
            <h6 class="xs-font mb-0">Которого мы придерживаемся</h6>
            <h3 class="section-title pb-4">Интерьер</h3>
        </div>
        <div style="text-align: center">
            {% for interior in interiors %}
                <a href="{% url 'houses:interior_gallery' %}?interior={{ interior.id }}"
                   class="text-decoration-none">
            <span class="badge {% if interior == active_interior %}badge-primary{% else %}badge-light{% endif %}"
                  style="font-size: 1rem;">
                {{ interior.name }}
            </span>
                </a>
            {% endfor %}
        </div>
        <br>
        <br>
        <div class="container">
            <div class="row no-gutters">
                {% for photo in photos %}
                    <div class="col-md-6 col-lg-4 item zoom-on-hover">
                        <a class="lightbox" href={{ photo.image.url }}>
                            <img class="img-fluid image scale-on-hover" src={{ photo.image.url }}>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <br>
        <br>
        <div style="text-align: center">
            <a class="btn btn-outline-primary btn-rounded" href={% url 'houses:home' %}>На главную</a>
        </div>
    </section>
{% endblock %}

templates/houses/news_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% include 'includes/navmenu.html' %}
{% block content %}
    <section class="section" id="news">
        <div class="container mb-3">
            <h6 class="xs-font mb-0">Рассказываем о последних событиях</h6>
            <h3 class="section-title mb-5">Новости</h3>
            {% for news in news_list %}
                <div class="blog-wrapper">
                    <div class="img-wrapper">
                        <img src="{{ news.main_photo.url }}" alt="{{ news.photo.name }}">
                        <div class="date-container">
                            <h6 class="day">{{ news.created_at|date:"j" }}</h6>
                            <h6 class="mun">{{ news.created_at|date:"M" }}</h6>
                        </div>
                    </div>
                    <div class="txt-wrapper">
                        <h4 class="blog-title">{{ news.name }}</h4>
                        <p>{{ news.description }}</p>
                    </div>
                </div>
                <br>
            {% endfor %}
            <br>
            <br>
        </div>
        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-lg justify-content-center">
                    {% for page_num in paginator.page_range %}
                        {% if page_num == page_obj.number %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ page_num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </nav>
        {% endif %}
        <div style="text-align: center">
            <a class="btn btn-outline-primary btn-rounded" href={% url 'houses:home' %}>На главную</a>
        </div>
    </section>
{% endblock %}

templates/includes/footer.html
<footer class="footer py-4 bg-light">
    <div class="container text-center">
        <p class="mb-4 small">
            <script>document.write(new Date().getFullYear())</script> &copy; <a
                href="#">Moscow Estate</a></p>
        {% include 'includes/socialmedia.html' %}
    </div>
</footer>

templates/includes/header.html
<header id="home" class="header">
    <div class="overlay"></div>

    <div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="container">
            <div class="carousel-inner">
                {% for text in header_texts %}
                    <div class="carousel-item {% if text.is_active %}active{% endif %}">
                        <div class="carousel-caption d-none d-md-block">
                            <h2 class="carousel-title">{{ text.title }}</h2>
                            <a class="btn btn-primary btn-rounded"
                               href={% url 'houses:house_list' %}>Дома</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="infos container mb-4 mb-md-2">
        <div class="title">
            <h5>Moscow Estate</h5>
            <p class="font-small">Загородные дома мечты</p>
        </div>
        <div class="socials text-right">
            <div class="row justify-content-between">
                <div class="col">
                    <a class="d-block subtitle"><i class="bi bi-telephone"></i>  {{ contact_info.phone }}</a>
                    <a class="d-block subtitle"><i class="bi bi-envelope"></i>    {{ contact_info.email }}</a>
                </div>
                <div class="col">
                    <h6 class="subtitle font-weight-normal mb-2">Социальные сети</h6>
                    {% include 'includes/socialmedia.html' %}
                </div>
            </div>
        </div>
    </div>
</header>

templates/includes/navmenu.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light bg-light rounded shadow mb-3">
    <div class="container">
        <a class="navbar-brand" href={% url 'houses:home' %}><img src={% static 'imgs/logo.svg' %} class="brand-img"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'houses:home' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'houses:house_list' %}">Дома</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'houses:interior_gallery' %}">Интерьер</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'houses:news_list' %}">Новости</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/includes/navmenu_main.html
{% load static %}
<nav id="scrollspy" class="navbar navbar-light bg-light navbar-expand-lg fixed-top" data-spy="affix"
     data-offset-top="20">
    <div class="container">
        <a class="navbar-brand" href={% url 'houses:home' %}><img src="{% static 'imgs/logo.svg' %}" class="brand-img"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#home">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#about">О нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#houses">Дома</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#interior">Интерьер</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#news">Новости</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">Контакты</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/includes/scroll_button.html
<button id="scrollToTopBtn" title="Наверх">
    <i class="bi bi-chevron-double-up"></i>
</button>

templates/includes/socialmedia.html
<div class="social-links">
    <a href="{{ contact_info.telegram }}" class="link pr-1"><i class="bi bi-telegram"></i></a>
    <a href="{{ contact_info.whatsapp }}" class="link pr-1"><i class="bi bi-whatsapp"></i></a>
    <a href="{{ contact_info.instagram }}" class="link pr-1"><i class="bi bi-instagram"></i></a>
</div>

templates/main.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Moscow Estate - turnkey country houses near Moscow">
    <meta name="author" content="Roman Pecheritsa">
    <title>{{ title }}</title>

    <link rel="stylesheet" href={% static 'vendors/owl-carousel/css/owl.carousel.css' %}>
    <link rel="stylesheet" href={% static 'vendors/owl-carousel/css/owl.theme.default.css' %}>
    <link rel="stylesheet" href={% static 'css/ollie.css' %}>
    <link rel="stylesheet" href="{% static 'icons/bootstrap-icons.css' %}">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

{% include 'includes/navmenu_main.html' %}
{% include 'includes/header.html' %}


<section class="section" id="about">
    <div class="container">
        <div class="row align-items-center mr-auto">
            <div class="col-md-4">
                <h3 class="section-title">О нас</h3>
                <p>Мы — компания Moscow Estate, специализирующаяся на строительстве загородных домов вашей мечты. Мы
                    создаем комфортное и качественное жилье, которое становится идеальным местом для жизни, отдыха и
                    вдохновения.</p>
            </div>
            <div class="col-sm-6 col-md-4 ml-auto">
                <div class="widget">
                    <div class="icon-wrapper">
                        <i class="bi bi-calendar-event"></i>
                    </div>
                    <div class="infos-wrapper">
                        <h4 class="text-primary">15+</h4>
                        <p>Лет на рынке</p>
                    </div>
                </div>
                <div class="widget">
                    <div class="icon-wrapper">
                        <i class="bi bi-emoji-smile"></i>
                    </div>
                    <div class="infos-wrapper">
                        <h4 class="text-primary">500+</h4>
                        <p>Довольных клиентов</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="widget">
                    <div class="icon-wrapper">
                        <i class="bi bi-house-check"></i>
                    </div>
                    <div class="infos-wrapper">
                        <h4 class="text-primary">200+</h4>
                        <p>Реализованных проектов</p>
                    </div>
                </div>
                <div class="widget">
                    <div class="icon-wrapper">
                        <i class="bi bi-people"></i>
                    </div>
                    <div class="infos-wrapper">
                        <h4 class="text-primary">50+</h4>
                        <p>Человек в команде</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% if main_houses %}
    <section class="section" id="houses">
        <div class="container">
            <h6 class="xs-font mb-0">Которые мы построили</h6>
            <h3 class="section-title pb-4">Дома</h3>
        </div>
        <div id="owl-portfolio" class="owl-carousel owl-theme mt-4">
            {% for house in main_houses %}
                <a href="{% url 'houses:house_detail'  house.pk %}" class="item expertises-item">
                    <img src="{{ house.main_photo.url }}" alt="{{ house.name }}">
                    <h6 class="mt-3 mb-2">{{ house.name }}</h6>
                    <p class="xs-font">{{ house.description|truncate_smart:200 }}</p>
                </a>
            {% endfor %}
        </div>
        <br>
        <br>
        <div style="text-align: center">
            <a class="btn btn-primary btn-rounded" href={% url 'houses:house_list' %}><i class="bi bi-house-check"></i>
                Все дома</a>
        </div>
    </section>
{% endif %}

{% if main_interiors %}
    <section class="section" id="interior">
        <div class="container">
            <h6 class="xs-font mb-0">Которого мы придерживаемся</h6>
            <h3 class="section-title mb-4">Интерьер</h3>

            <div class="row text-center">
                {% for interior in main_interiors %}
                    <div class="col-lg-4">
                        <a href="{% url 'houses:interior_gallery' %}?interior={{ interior.id }}"
                           class="card border-0 text-dark">
                            <img class="card-img-top" src="{{ interior.main_photo.url }}" alt="{{ interior.name }}">
                            <span class="card-body">
                        <h4 class="title mt-4">{{ interior.name }}</h4>
                        <p class="xs-font">{{ interior.description }}</p>
                    </span>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <br>
        <br>
        <div style="text-align: center">
            <a class="btn btn-primary btn-rounded" href="{% url 'houses:interior_gallery' %}"><i class="bi bi-lamp"></i>
                Все интерьеры</a>
        </div>
    </section>
{% endif %}

{% if main_news %}
    <section class="section" id="news">
        <div class="container mb-3">
            <h6 class="xs-font mb-0">Рассказываем о последних событиях</h6>
            <h3 class="section-title mb-5">Новости</h3>
            <div class="blog-wrapper">
                <div class="img-wrapper">
                    <img src="{{ main_news.main_photo.url }}" alt="{{ main.photo.name }}">
                    <div class="date-container">
                        <h6 class="day">{{ main_news.created_at|date:"j" }}</h6>
                        <h6 class="mun">{{ main_news.created_at|date:"M" }}</h6>
                    </div>
                </div>
                <div class="txt-wrapper">
                    <h4 class="blog-title">{{ main_news.name }}</h4>
                    <p>{{ main_news.description }}</p>
                </div>
            </div>
            <br>
            <br>
        </div>
        <div style="text-align: center">
            <a class="btn btn-primary btn-rounded" href="{% url 'houses:news_list' %}"><i class="bi bi-newspaper"></i>
                Все новости</a>
        </div>
    </section>
{% endif %}

<section id="contact" class="section pb-0">

    <div class="container">
        <h3 class="section-title mb-5">Контакты</h3>

        <div class="row align-items-center justify-content-between">
            <div class="col-md-8 col-lg-7">
                <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A1c1adec72200a7514dcca0746a29e55fcba32f53eff4429de632c6fbf64839f4&amp;source=constructor"
                        width="100%" height="387" frameborder="0"></iframe>
            </div>
            <div class="col-md-4 d-none d-md-block order-1">
                <ul class="list">
                    <li class="list-head">
                        <h6>Контактная информация</h6>
                    </li>
                    <li class="list-body">
                        <p class="py-2"><i class="bi bi-geo-alt"></i>{{ contact_info.address }}</p>
                        <p class="py-2"><i class="bi bi-envelope"></i>{{ contact_info.email }}</p>
                        <p class="py-2"><i class="bi bi-telephone"></i>{{ contact_info.phone }}</p>

                    </li>
                </ul>
            </div>
        </div>

        {% include 'includes/footer.html' %}
    </div>
</section>
{% include 'includes/scroll_button.html' %}
<script src={% static 'vendors/jquery/jquery-3.4.1.js' %}></script>
<script src={% static 'vendors/bootstrap/bootstrap.bundle.js' %}></script>
<script src={% static 'vendors/bootstrap/bootstrap.affix.js' %}></script>
<script src={% static 'vendors/owl-carousel/js/owl.carousel.js' %}></script>
<script src={% static 'js/ollie.js' %}></script>

</body>
</html>